### ISSUE TITLE
Compilation error with arduino R4

### ISSUE THREAD

**Issue by gluon** [danmowehhuk/AD75019#1]
Hi,

we are trying to compile a code for arduino R4.

When we do #include <AD75019.h> (only, without anything related to the library elsewhere in the code) , it doesn't compile.

If we remove this include, it compiles.

Did you experience it on Arduino R4 ? Maybe this is related to this version ?

The error is :

**/Users/julien/Documents/Arduino/libraries/AD75019/src/AD75019.cpp: In constructor 'AD75019::AD75019(uint8_t, uint8_t, uint8_t)':
/Users/julien/Documents/Arduino/libraries/AD75019/src/AD75019.cpp:25:96: error: invalid conversion from 'void (*)(uint8_t) {aka void (*)(unsigned char)}' to 'AD75019::voidFuncCallback_t {aka void (*)(unsigned char, unsigned char)}' [-fpermissive]
   _pinModeCallback(_ad75019_pinModeDefault), _digitalWriteCallback(_ad75019_digitalWriteDefault) {}
                                                                                                ^

exit status 1

Compilation error: exit status 1**

**Comment by danmowehhuk** [comment]
Hi @gluon - I'm sorry to hear your running into trouble with this library. Are you able to compile any of the examples packaged with the library? Let me know what version of the Arduino IDE you're using, too, please.

**Comment by gluon** [comment]
No. None examples were compiling.

We  found a workaround, and fixed it.

In AD75019.cpp, I did this: 
void _ad75019_pinModeDefault(uint8_t pinNumber, uint8_t /* unused */) {
  pinMode(pinNumber, OUTPUT);
}

**Comment by danmowehhuk** [comment]
Apologies for that. This is fixed in version 1.0.2
